import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  metadataBase: new URL('https://skill-swaps.vercel.app'),
  title: {
    default: 'SkillSwap - Exchange Skills, Grow Together',
    template: '%s | SkillSwap'
  },
  description: 'SkillSwap is a platform where you can exchange skills with others. Learn new skills by teaching what you know. Join our community and grow together.',
  keywords: [
    'skill exchange',
    'skill swap',
    'learn skills',
    'teach skills',
    'online learning',
    'skill sharing',
    'peer learning',
    'skillswap',
    'skill trade',
    'knowledge exchange'
  ],
  authors: [{ name: 'SkillSwap Team' }],
  creator: 'SkillSwap',
  publisher: 'SkillSwap',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://skill-swaps.vercel.app',
    siteName: 'SkillSwap',
    title: 'SkillSwap - Exchange Skills, Grow Together',
    description: 'Join SkillSwap to exchange skills with others. Learn new skills by teaching what you know.',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'SkillSwap - Exchange Skills Platform',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SkillSwap - Exchange Skills, Grow Together',
    description: 'Join SkillSwap to exchange skills with others. Learn new skills by teaching what you know.',
    images: ['/og-image.png'],
  },
  verification: {
    google: 'UUH6H-m0Ln5mbXGVHExiLn9HInS278-eYv3zCsh853s',
  },
  alternates: {
    canonical: 'https://skill-swaps.vercel.app',
  },
  icons: {
    icon: [
      {
        url: "/assets/images/logo.png",
        type: "image/png",
      },
    ],
    shortcut: "/assets/images/logo.png",
    apple: "/assets/images/logo.png",
  },
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 9a6ccbef1ff2fca03f33a1759791d6c7d2d17b3f
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Additional meta tags */}
        <meta name="application-name" content="SkillSwap" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="SkillSwap" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="theme-color" content="#1F426E" />
        
        {/* JSON-LD Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "name": "SkillSwap",
              "description": "Exchange skills with others and grow together",
              "url": "https://skill-swaps.vercel.app",
              "potentialAction": {
                "@type": "SearchAction",
                "target": "https://skill-swaps.vercel.app/search?q={search_term_string}",
                "query-input": "required name=search_term_string"
              }
            })
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "SkillSwap",
              "url": "https://skill-swaps.vercel.app",
              "logo": "https://skill-swaps.vercel.app/assets/images/logo.png",
              "description": "A platform for exchanging skills and knowledge"
            })
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
